name: ItemizerX
version: ${project.version}
api-version: 1.19
description: A rewrite of Itemizer
author: unsuperiordev (Focusvity)
main: me.focusvity.itemizerx.ItemizerX
softdepend:
  - CoreProtect
commands:
  itemizer:
    description: The main command for ItemizerX
    usage: /<command>
    aliases: [ii, it]
